### PR TITLE
Adds IridescentView library

### PR DESCRIPTION
**Pull request by alexandrehtrb**
Hello,

I would like to add the IridescentView library.

### CODE REVIEW

**Comment by waandroid** [comment]
would like to add the IridescentView library as well

**Comment by alexandrehtrb** [comment]
@wasabeef @pgreze , could you please review whether this is a good addition for the list?

**Comment by pgreze** [comment]
@alexandrehtrb thank you for adding this new library.
I think there's several other improvements that should be done before merging it:
1. jcenter will be [closed soon](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). At least for new projects, they should use a more future-proof publication channels (like Maven Central)
2. default README is not in English. I would advise to use it as the default language before pushing it in this EN first library collection.

**Comment by alexandrehtrb** [comment]
Hello @pgreze ,

I took care of the improvements you mentioned!
The library is now available on Maven Central and the default README is in english.

**Comment by pgreze** [comment]
@alexandrehtrb thank you for addressing comments.

**Pull request merged**
