### PR TITLE
contributing android ui

### PR DESCRIPTION
**Pull request by MinhyeokOh**
Hello, I developed a UI that allows users to quickly find photos stored in Android galleries using tag information, date information, and location information taken, and I would like to contribute the developed UI to this project. I uploaded rough simulation videos on readme.md, so please check my project repository!

### CODE REVIEW

**Comment by xudadi** [comment]
您好，我已收到您的邮件，我会尽快处理，感谢！

**Comment by MinhyeokOh** [comment]
> 您好，我已收到您的邮件，我会尽快处理，感谢！

When would be possible to give me some feedback? Actually, I have to do presentation in my university at June 7th, so I'd appreciate it if you could give feedback as soon as possible!

**Comment by MinhyeokOh** [comment]
> 您好，我已收到您的邮件，我会尽快处理，感谢！

When would be possible to give me some feedback? I have to do final presentation in my university at June 7th, so I'd appreciate it if you could give feedback as soon as possible!

**Comment by MinhyeokOh** [comment]
When would be possible to give me some feedback? I have to make a final
presentation in university at June 7th, so I'd appreciate it if you could
give feedback as soon as possible!

(You can check my UI if you find ImageSearchLayout in readme.md)

2023년 5월 27일 (토) 오후 8:30, Xudadi ***@***.***>님이 작성:

**Comment by jinusong** [comment]
@MinhyeokOh 
Hello, I'm not the repository owner, but I think I should inform you, so I'm writing a comment.
I understand that this repository is a place where the information of the android UI/UX library is gathered.
I saw the repository you uploaded, but it was made in the form of an app project, not a library.
So I wonder if it will be difficult for the PR to merge.

You seem to be busy with your college assignment schedule. Why don't you contribute to an open source other than here?

안녕하세요, 제가 해당 repository owner 아니지만 알려드려야 할 것 같아서 코멘트를 남겨봅니다.
이 레포지토리는 android UI/UX 라이브러리의 정보를 모아둔 곳으로 알고 있습니다.
올려주신 레포지토리를 보았는데요, 애초에 라이브러리가 아닌 앱 프로젝트 형태로 만들어져 있더라구요.
그래서 해당 PR은 머지되기 어렵지 않을까 싶습니다.

대학과제 일정 때문에 바쁘신 것 같은데, 여기가 아닌 다른 오픈소스에 컨트리뷰트 해보시는 건 어떠실까요?

**Pull request closed without merging**
