### PR TITLE
implemented expandable bottom bar to menu section.

### PR DESCRIPTION
**Pull request by st235**

### CODE REVIEW

**Comment by st235** [comment]
@wasabeef, @ogaclejapan  can you please review this PR

**Comment by st235** [comment]
@wasabeef, any chances to get approval?

**Comment by wasabeef** [comment]
@st235 
Can you change the README.md file too?

**Comment by st235** [comment]
@wasabeef, yeah, of course!

**Comment by st235** [comment]
@wasabeef, `README.md` changed 🙂
Anyway, thank you for a replay!

**Comment by wasabeef** [comment]
@st235 
Great works. 🚢

**Comment by st235** [comment]
@wasabeef 
Thank you 🎉

**Comment by wasabeef** [comment]
I'm sorry for the too late reply. 🤕

**Comment by st235** [comment]
no problems)

**Pull request merged**
