### PR TITLE
Added awesome android libraries

### PR DESCRIPTION
**Pull request by FareesHussain**
Awesome libraries from skydoves.

### CODE REVIEW

**Review by pgreze — CHANGES_REQUESTED** [review]
A lot of good ones 👍 

Could you check again the image for `Transformation Layout`? It seems broken when showing the README.

**Comment by FareesHussain** [comment]
OK

**Comment by FareesHussain** [comment]
Done please check

**Review by pgreze — APPROVED** [review]
Thank you for fixing the image.

**Pull request merged**
