### PR TITLE
Added Voice Overlay

### PR DESCRIPTION
**Pull request by PLNech**
**Voice overlay** is an **open-source** library helping you get your user's voice input as text, handling both **permission request** and **speech to text**. It provides out of the box a functional, polished UX, and provides several **customization options** to let you tweak the experience you want to provide :slightly_smiling_face:

### CODE REVIEW

**Comment by PLNech** [comment]
Hey @wasabeef, do you still maintain this lists? :slightly_smiling_face:

**Comment by PLNech** [comment]
Hi @pgreze, thanks for replying to this Pull Request - could you explain why closing it without merging ?

**Comment by pgreze** [comment]
@PLNech hi, sorry for closing your PR without commenting it, I was wishing to explain why in each PR but it's not an easy task.
In a few words, in order to maintain easily the repository I closed all PRs older than a certain date because they all had conflicts.
If you still want to submit it, please open a new PR and we would be happy to review it 👍

**Comment by PLNech** [comment]
Hi @pgreze, thanks for the explanation - no worries, I know how tedious this kind of maintenance work can be :upside_down_face: 

Congrats on reviving this repository!

My PR is reopened as #296, with conflicts solved - let's continue the conv there :slightly_smiling_face:

**Pull request closed without merging**
