### PR TITLE
Add AnimatedBottomBar library

### PR DESCRIPTION
**Pull request by Droppers**
Not sure if allowed, but I have added my own library: https://github.com/Droppers/AnimatedBottomBar

Also, completely unrelated, wouldn't it make more sense if these lists were alphabetically sorted? Maybe in the form of a GitHub action that runs a script sorting the Markdown tables? Not sure how realistic this would be tough, just an idea.

Edit: pretty easy, made a script that sorts the README file:
https://gist.github.com/Droppers/6c4d401d201353bd032f829eec12b95f

### CODE REVIEW

**Review by pgreze — CHANGES_REQUESTED** [review]
Please make sure your 2 images are displayed correctly on 1 line.

About sorting the README, there's plans to use something more fair than an alphabetic order, but thx for the suggestion.

**Comment by Droppers** [comment]
@pgreze  I'm not sure what you mean by that, since the height is a lot smaller than the width, it makes more sense for them to be placed underneath each other?

**Comment by pgreze** [comment]
@Droppers in any case, only 1 gif is displayed. 
I can also look at similar preview images in the same section, they could put both horizontal images without losing the effect.

**Comment by Droppers** [comment]
Do you mean changing the width of the gifs to 50%? Sorry for the misunderstanding, but I am just confused why that would be beneficial, the gifs underneath each other take up half the vertical space of the majority of all other libraries 😅? But if having multiple gifs is a problem, I can remove the second gif.

**Comment by pgreze** [comment]
@Droppers have 2 gifs is not an issue, I'm just comparing your new addition:

Screen Shot 2021-01-06 at 10 05 11

With for example this existing line that could add 2 gifs in 1 line without compromising on the final result:

Screen Shot 2021-01-06 at 10 05 20

You can access the Markdown preview by clicking `Files Changed` > Click the `...` button for the README.md > `View file` redirecting to https://github.com/wasabeef/awesome-android-ui/blob/a9c32ebab256ddaf6a52b04be5ce358f093ae085/README.md

**Comment by Droppers** [comment]
Those images are only on one line due to their small resolutions, seems to be a coincidence they are on the same line for you 😄 .

This is how it looks for me:
image

But I have changed it so the GIFs are on one line now.

**Review by pgreze — APPROVED** [review]
Thx for addressing comments 👍

**Pull request merged**
