### PR TITLE
removed incorrect image.

### PR DESCRIPTION
**Pull request by gogeta95**

### CODE REVIEW

**Comment by carolinaknoll** [comment]
Nice! There was a mistyped japanese character there. I have a project that uses awesome lists and was wondering for a few days why this little typo was still there. I wish it was easier to merge small fixes like this one, like with some kind of voting functionality that wouldn't need a direct approval of the repo owner for merging.

**Comment by bosssqueen23** [comment]
Can we please remove this from my device it’s a invasion of privacy

**Comment by carolinaknoll** [comment]
Hi there @bosssqueen23 , I couldn't understand what you mean. 

Is it that you want to stop receiving e-mails about this Pull Request? If it is, you can safely click on the url below where 'mute the thread' is on the e-mail you received to stop receiving new e-mails about it. You might have clicked on subscribe by mistake, but don't worry, it happens. Please let me know if you need more help.

**Comment by wasabeef** [comment]
@carolinaknoll 

Thanks. I'm sorry for my soooo late replay.

**Comment by carolinaknoll** [comment]
@wasabeef not a problem at all! I'm glad you looked into this, I had forgotten about it! 😄 🚀

**Comment by gogeta95** [comment]
Wow, thank you.

**Comment by wasabeef** [comment]
@gogeta95 Thank you 😺

**Pull request merged**
