### PR TITLE
Added SSComposeCookBook [Compose collections]

### PR DESCRIPTION
**Pull request by yashwantGowla**
A Collection of major Jetpack compose UI components which are commonly used.

### CODE REVIEW

**Comment by yashwantGowla** [comment]
@wasabeef Please have a look

**Comment by yashwantGowla** [comment]
@wasabeef @pgreze Any update?

**Comment by mobile-simformsolutions** [comment]
> @wasabeef @pgreze Any update?

**Comment by yashwantGowla** [comment]
@wasabeef Please have a look.

**Comment by yashwantGowla** [comment]
@wasabeef Kindly look into this one.

**Comment by yashwantGowla** [comment]
@wasabeef Kindly look into this one. @pgreze  Can you spare some time for this?

**Comment by wasabeef** [comment]
@yashwantGowla Thanks! and sorry for late reply.

**Comment by yashwantGowla** [comment]
Hello buddy

Thank you so much!

**Comment by 416542923** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by zz3100201** [comment]
您的邮件我已收到。

**Pull request merged**
